apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: todoapp-ui
  template:
    metadata:
      labels:
        app: todoapp-ui
    spec:
      containers:
      - image: vivekcs0114/todoapp-ui:v1.2
        name: todoapp-ui
        ports:
        - containerPort: 3000
